name: C/C++ CI

on: [push]

jobs:
  ubuntu-build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v4
    
    - name: Set up Clang
      uses: egor-tensin/setup-clang@v1
      with:
        version: latest
        platform: x64
    - name: Build
      run: clang++ Furby.cpp -o Furby
    - name: Upload Furby executable
      uses: actions/upload-artifact@v4
      with:
        name: Furby
        path: Furby
